# l10n_ja パッケージの analysis_options.yaml
# Dart-only package なので lints を使用
include: package:lints/recommended.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
