name: hokyoksei
packages:
  - apps/**
  - packages/**

command:
  bootstrap:
    usePubspecOverrides: true
  version:
    branch: main

scripts:
  verify:
    run: |
      melos bootstrap
      melos run analyze
      melos run test
    description: Bootstrap workspace, then run analyze and test

  analyze:
    run: |
      (cd apps/dangi_app && flutter analyze)
      dart analyze packages/shared_core packages/l10n_ja packages/motion_tokens packages/ui_tokens
    description: Run Dart analyzer for all packages

  format:
    run: dart format .
    description: Format all Dart files

  test:
    run: |
      (cd apps/dangi_app && flutter test)
      (cd packages/shared_core && dart test)
    description: Run tests for all packages
